name: Build and push docker image

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: Build latest docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - name: Build docker image
        run: nix-build ./dockerfile.nix
      - name: Assure that image size is smaller than 35MB
        run: test $(du -L result | awk '{print $1}') -lt 35000
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: |
          docker load -i result
          docker push foldu/kairowiki:latest
