name: Build and push docker image

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: Build latest docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - run: nix-build ./dockerfile.nix
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker load -i result
          docker push foldu/kairowiki:latest
